# This file was generated by		
# Qfsm Version 0.44			
# (C) Stefan Duffner			


%%{
machine asdfsd;

main :=
start:
State_0: (
  [\[\]a] @accept  -> State_1),
State_1: (
  "" @not_accept -> final);

}%%
