# This file was generated by		
# Qfsm Version 0.44			
# (C) Stefan Duffner			


%%{
machine klee;

main :=
start:
first: (
  [+\-] @not_accept  -> plus_minus | 
  digit @accept  -> digit_before | 
  ( ^(digit) & [^+\--.] ) @not_accept  -> no_int | 
  [.] @not_accept  -> point),
plus_minus: (
  digit @accept  -> digit_before | 
  ( ^(digit) & [^.] ) @not_accept  -> no_int | 
  [.] @not_accept  -> point),
digit_before: (
  digit @accept  -> digit_before | 
  ( ^(digit) & [^.] ) @not_accept  -> no_int | 
  [.] @not_accept  -> point),
no_int: (
  any @not_accept  -> no_int),
point: (
  ^(digit) @not_accept  -> no_int | 
  digit @accept  -> digit_after),
digit_after: (
  ^(digit) @not_accept  -> no_int | 
  digit @accept  -> digit_after);

}%%
